# Site settings
title: Compute Canadian
email: info@compute-canadian.ca
url: http://www.compute-canadian.ca.s3-website.ca-central-1.amazonaws.com
description: "Building a successful and federal computational research enterprise, together"
skills: "We can build a successful and federal computational research enterprise, together"
meta_author: Compute Canadian

future: true

# Google webmaster tools
google_verify: "Rss2PQg3cWxCqZZ3HYy5an9MaKKeTz1GtdL4vT-_xQM"

# Contact form:
#- static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff 
  primary-rgb: "255,255,255" 
  secondary: cc0010 #FD6E8A
  secondary-dark: ff0020  #A2122F

# Footer settings
footer:
  copyright: Compute Canadian
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/compute_canadian
  - title: envelope
    url: mailto:info@compute_canadian.ca
  - title: rss
    url: /feed.xml

# Postal address (add as many lines as necessary)
#address:
#  - line: Across Canada

# Credits content
#credits: 

# Build settings
markdown: kramdown
permalink: pretty

include: [ "discussion-paper", "files" ]
